// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: copyColorSet
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("copyColorSet")]
    public sealed class MayaGenerated_CopyColorSetNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (copyColorSet)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string sourceSet;
        [SerializeField] private string destinationSet;
        [SerializeField] private bool replaceDestination = true;

        [SerializeField] private string incomingMesh;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            sourceSet = ReadString("", ".sourceSet", "sourceSet", ".srcSet", "srcSet", ".source", "source");
            destinationSet = ReadString("", ".destinationSet", "destinationSet", ".dstSet", "dstSet", ".destination", "destination");
            replaceDestination = ReadBool(true, ".replaceDestination", "replaceDestination", ".replace", "replace");

            incomingMesh = FindLastIncomingTo("inputMesh", "inMesh", "input", "in", "worldMesh");
            string im = string.IsNullOrEmpty(incomingMesh) ? "none" : incomingMesh;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, src='{sourceSet}', dst='{destinationSet}', replace={replaceDestination}, incomingMesh={im} (copy not executed; intent preserved)");
        }
    }
}
