// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: axisFromMatrixDL
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("axisFromMatrixDL")]
    public sealed class MayaGenerated_AxisFromMatrixDLNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool hasMatrix;
        [SerializeField] private Matrix4x4 matrix;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            hasMatrix =
                TryReadMatrix4x4(".inputMatrix", out matrix) ||
                TryReadMatrix4x4("inputMatrix", out matrix) ||
                TryReadMatrix4x4(".matrix", out matrix) ||
                TryReadMatrix4x4("matrix", out matrix);

            incomingPlug = FindLastIncomingTo("inputMatrix", "inMatrix", "matrix");
            SetNotes($"{NodeType} '{NodeName}' decoded: hasMatrix={hasMatrix}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
