// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blendFalloff
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blendFalloff")]
    public sealed class MayaGenerated_BlendFalloffNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blendFalloff)")]
        [SerializeField] private float falloff;
        [SerializeField] private int mode;
        [SerializeField] private string incomingFalloff;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            falloff = ReadFloat(0f, ".falloff", "falloff", ".f", "f");
            mode = ReadInt(0, ".mode", "mode", ".operation", "operation");

            incomingFalloff = FindLastIncomingTo("falloff", "f");

            SetNotes($"{NodeType} '{NodeName}' decoded: falloff={falloff}, mode={mode}, incomingFalloff={(string.IsNullOrEmpty(incomingFalloff) ? "none" : incomingFalloff)}");
        }
    }
}
