// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyAbsFloatOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyAbsFloatOverride")]
    public sealed class MayaGenerated_ApplyAbsFloatOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float value;
        [SerializeField] private string sampleIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            value = ReadFloat(0f, ".value", "value", ".floatValue", "floatValue", ".v", "v");
            sampleIncomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, value={value}, incoming={(string.IsNullOrEmpty(sampleIncomingPlug) ? "none" : sampleIncomingPlug)}");
        }
    }
}
