// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: brownian
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("brownian")]
    public sealed class MayaGenerated_BrownianNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (brownian)")]
        [SerializeField] private float amplitude = 1f;
        [SerializeField] private float frequency = 1f;
        [SerializeField] private int seed;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            amplitude = ReadFloat(1f, ".amplitude", "amplitude", ".amp", "amp");
            frequency = ReadFloat(1f, ".frequency", "frequency", ".freq", "freq");
            seed = ReadInt(0, ".seed", "seed");

            SetNotes($"{NodeType} '{NodeName}' decoded: amp={amplitude}, freq={frequency}, seed={seed} (no runtime noise sim; attrs+connections preserved)");
        }
    }
}
