// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletSoftBodyShape
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletSoftBodyShape")]
    public sealed class MayaGenerated_BulletSoftBodyShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletSoftBodyShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float mass = 1f;
        [SerializeField] private float damping;
        [SerializeField] private float stiffness;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            mass = ReadFloat(1f, ".mass", "mass", ".m", "m");
            damping = ReadFloat(0f, ".damping", "damping", ".dmp", "dmp");
            stiffness = ReadFloat(0f, ".stiffness", "stiffness", ".k", "k");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mass={mass}, damping={damping}, stiffness={stiffness} (no runtime bullet sim; attrs+connections preserved)");
        }
    }
}
