// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: baseLattice
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("baseLattice")]
    public sealed class MayaGenerated_BaseLatticeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (baseLattice)")]
        [SerializeField] private int divisionsS;
        [SerializeField] private int divisionsT;
        [SerializeField] private int divisionsU;
        [SerializeField] private string incomingGeometry;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            divisionsS = ReadInt(0, ".sDivisions", "sDivisions", ".divisionsS", "divisionsS", ".s", "s");
            divisionsT = ReadInt(0, ".tDivisions", "tDivisions", ".divisionsT", "divisionsT", ".t", "t");
            divisionsU = ReadInt(0, ".uDivisions", "uDivisions", ".divisionsU", "divisionsU", ".u", "u");

            incomingGeometry = FindLastIncomingTo("input", "in", "inputGeometry", "inputGeom");

            SetNotes($"{NodeType} '{NodeName}' decoded: divS={divisionsS}, divT={divisionsT}, divU={divisionsU}, incomingGeom={(string.IsNullOrEmpty(incomingGeometry) ? "none" : incomingGeometry)}");
        }
    }
}
