// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: buttonManip
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("buttonManip")]
    public sealed class MayaGenerated_ButtonManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (buttonManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string label;
        [SerializeField] private int state;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            label = ReadString("", ".label", "label", ".text", "text", ".name", "name");
            state = ReadInt(0, ".state", "state", ".value", "value");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, label='{label}', state={state}");
        }
    }
}
