// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: arrowManip
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("arrowManip")]
    public sealed class MayaGenerated_ArrowManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float size;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            size = ReadFloat(0f, ".size", "size", ".s", "s");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, size={size}");
        }
    }
}
