// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blendTwoAttr
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blendTwoAttr")]
    public sealed class MayaGenerated_BlendTwoAttrNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blendTwoAttr)")]
        [SerializeField] private float blender = 0.5f;
        [SerializeField] private float input0;
        [SerializeField] private float input1;
        [SerializeField] private string incomingBlender;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            blender = ReadFloat(0.5f, ".attributesBlender", "attributesBlender", ".blender", "blender", ".ab", "ab");
            input0 = ReadFloat(0f, ".input[0]", "input[0]", ".input0", "input0", ".i0", "i0");
            input1 = ReadFloat(0f, ".input[1]", "input[1]", ".input1", "input1", ".i1", "i1");

            incomingBlender = FindLastIncomingTo("attributesBlender", "blender", "ab");

            SetNotes($"{NodeType} '{NodeName}' decoded: blender={blender}, in0={input0}, in1={input1}, incomingBlender={(string.IsNullOrEmpty(incomingBlender) ? "none" : incomingBlender)}");
        }
    }
}
