// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bezierCurveToNurbs
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bezierCurveToNurbs")]
    public sealed class MayaGenerated_BezierCurveToNurbsNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bezierCurveToNurbs)")]
        [SerializeField] private bool keepBeziers;
        [SerializeField] private bool enabled = true;
        [SerializeField] private string incomingCurve;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            keepBeziers = ReadBool(false, ".keepBeziers", "keepBeziers", ".keep", "keep");

            incomingCurve = FindLastIncomingTo("inputCurve", "ic", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, keepBeziers={keepBeziers}, incomingCurve={(string.IsNullOrEmpty(incomingCurve) ? "none" : incomingCurve)}");
        }
    }
}
