// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorMath
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorMath")]
    public sealed class MayaGenerated_ColorMathNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorMath)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int operation;
        [SerializeField] private float factor = 1f;

        [SerializeField] private string incomingA;
        [SerializeField] private string incomingB;
        [SerializeField] private string incomingFactor;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            operation = ReadInt(0, ".operation", "operation", ".op", "op", ".mode", "mode");
            factor = ReadFloat(1f, ".factor", "factor", ".f", "f");

            incomingA = FindLastIncomingTo("colorA", "a", "inputA", "inA");
            incomingB = FindLastIncomingTo("colorB", "b", "inputB", "inB");
            incomingFactor = FindLastIncomingTo("factor", "f");

            string ia = string.IsNullOrEmpty(incomingA) ? "none" : incomingA;
            string ib = string.IsNullOrEmpty(incomingB) ? "none" : incomingB;
            string ifa = string.IsNullOrEmpty(incomingFactor) ? "none" : incomingFactor;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, op={operation}, factor={factor}, incomingA={ia}, incomingB={ib}, incomingFactor={ifa} (shader eval not simulated)");
        }
    }
}
