// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blendDevice
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blendDevice")]
    public sealed class MayaGenerated_BlendDeviceNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blendDevice)")]
        [SerializeField] private float blend = 0.5f;
        [SerializeField] private float weight = 1f;
        [SerializeField] private string incomingBlend;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            blend = ReadFloat(0.5f, ".blend", "blend", ".b", "b");
            weight = ReadFloat(1f, ".weight", "weight", ".w", "w");

            incomingBlend = FindLastIncomingTo("blend", "b");

            SetNotes($"{NodeType} '{NodeName}' decoded: blend={blend}, weight={weight}, incomingBlend={(string.IsNullOrEmpty(incomingBlend) ? "none" : incomingBlend)}");
        }
    }
}
