// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: attachSurface
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("attachSurface")]
    public sealed class MayaGenerated_AttachSurfaceNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float parameterU;
        [SerializeField] private float parameterV;
        [SerializeField] private string inputIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            parameterU = ReadFloat(0f, ".parameterU", "parameterU", ".u", "u");
            parameterV = ReadFloat(0f, ".parameterV", "parameterV", ".v", "v");
            inputIncomingPlug = FindLastIncomingTo("inputSurface", "is", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: (u,v)=({parameterU},{parameterV}), incoming={(string.IsNullOrEmpty(inputIncomingPlug) ? "none" : inputIncomingPlug)}");
        }
    }
}
