// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: arrayMapper
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("arrayMapper")]
    public sealed class MayaGenerated_ArrayMapperNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private int size;
        [SerializeField] private string inputIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            size = ReadInt(0, ".size", "size", ".arraySize", "arraySize");
            inputIncomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: size={size}, incoming={(string.IsNullOrEmpty(inputIncomingPlug) ? "none" : inputIncomingPlug)}");
        }
    }
}
