// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bevel
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bevel")]
    public sealed class MayaGenerated_BevelNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bevel)")]
        [SerializeField] private float offset;
        [SerializeField] private int segments;
        [SerializeField] private bool enabled = true;
        [SerializeField] private string incomingCurve;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            offset = ReadFloat(0f, ".offset", "offset", ".width", "width", ".w", "w");
            segments = ReadInt(0, ".segments", "segments", ".divisions", "divisions", ".seg", "seg");

            incomingCurve = FindLastIncomingTo("inputCurve", "ic", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, offset={offset}, segments={segments}, incomingCurve={(string.IsNullOrEmpty(incomingCurve) ? "none" : incomingCurve)}");
        }
    }
}
