// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: componentManip
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("componentManip")]
    public sealed class MayaGenerated_ComponentManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (componentManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float size = 1f;
        [SerializeField] private int mode;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            size = ReadFloat(1f, ".size", "size", ".s", "s");
            mode = ReadInt(0, ".mode", "mode", ".m", "m");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, size={size}, mode={mode}");
        }
    }
}
