// MAYAIMPORTER_PATCH_V5: Markdown import report generator for validation / portfolio proof
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MayaImporter.Core
{
    /// <summary>
    /// Generates a deterministic Markdown report from MayaSceneData and MayaImportLog.
    /// The report is intentionally dependency-light so it can be used in Editor validation,
    /// CI-style parser checks, and portfolio proof screenshots.
    /// </summary>
    public static class MayaImportReport
    {
        public static string WriteMarkdownReport(MayaSceneData scene, MayaImportOptions options, MayaImportLog log, string importedRootName = null)
        {
            options ??= new MayaImportOptions();
            string folder = ResolveReportFolder(options.ReportOutputFolder);
            Directory.CreateDirectory(folder);

            string baseName = "MayaImportReport";
            if (!string.IsNullOrEmpty(scene?.SourcePath))
                baseName = Path.GetFileNameWithoutExtension(scene.SourcePath);

            string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            string safeBaseName = MakeSafeFileName(baseName);
            string path = Path.Combine(folder, safeBaseName + "_ImportReport_" + timestamp + ".md");
            File.WriteAllText(path, BuildMarkdown(scene, options, log, importedRootName), Encoding.UTF8);

#if UNITY_EDITOR
            try
            {
                string projectPath = Directory.GetCurrentDirectory().Replace('\\', '/');
                string normalized = path.Replace('\\', '/');
                if (normalized.StartsWith(projectPath + "/", StringComparison.OrdinalIgnoreCase))
                {
                    string assetPath = normalized.Substring(projectPath.Length + 1);
                    UnityEditor.AssetDatabase.ImportAsset(assetPath);
                }
            }
            catch { }
#endif

            log?.Info("Import report written: " + path);
            return path;
        }

        public static string BuildMarkdown(MayaSceneData scene, MayaImportOptions options, MayaImportLog log, string importedRootName = null)
        {
            options ??= new MayaImportOptions();
            var sb = new StringBuilder(64 * 1024);

            sb.AppendLine("# MAYAtoUnity Import Report");
            sb.AppendLine();
            sb.AppendLine("This report is generated by `MayaImportReport` to make each import auditable and reproducible.");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();

            AppendSummary(sb, scene, log, importedRootName);
            AppendSourceEvidence(sb, scene);
            AppendCoverage(sb, scene);
            if (options.ReportNodeTypeBreakdown) AppendNodeTypeBreakdown(sb, scene, options.ReportNodeTypeMaxEntries);
            if (options.ReportProvenanceBreakdown) AppendProvenanceBreakdown(sb, scene);
            if (options.ReportUnsupportedNodes) AppendUnsupportedNodes(sb, scene, options.ReportUnsupportedNodeMaxEntries);
            AppendStructuredCommandCounts(sb, scene);
            AppendLog(sb, log);
            AppendValidationChecklist(sb, scene);
            AppendDisclaimer(sb);

            return sb.ToString();
        }

        private static void AppendSummary(StringBuilder sb, MayaSceneData scene, MayaImportLog log, string importedRootName)
        {
            sb.AppendLine("## 1. Summary");
            sb.AppendLine();
            sb.AppendLine("| Item | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Source path | `" + EscapeTable(scene?.SourcePath) + "` |");
            sb.AppendLine("| Source kind | " + (scene != null ? scene.SourceKind.ToString() : "null") + " |");
            sb.AppendLine("| Schema version | " + (scene != null ? scene.SchemaVersion.ToString() : "-" ) + " |");
            sb.AppendLine("| Imported root | `" + EscapeTable(importedRootName ?? "") + "` |");
            sb.AppendLine("| Node count | " + (scene?.Nodes?.Count ?? 0) + " |");
            sb.AppendLine("| Connection count | " + (scene?.Connections?.Count ?? 0) + " |");
            sb.AppendLine("| Raw statement count | " + (scene?.RawStatements?.Count ?? 0) + " |");
            sb.AppendLine("| Warnings | " + (log?.Warnings?.Count ?? 0) + " |");
            sb.AppendLine("| Errors | " + (log?.Errors?.Count ?? 0) + " |");
            sb.AppendLine();
        }

        private static void AppendSourceEvidence(StringBuilder sb, MayaSceneData scene)
        {
            sb.AppendLine("## 2. Source evidence");
            sb.AppendLine();
            sb.AppendLine("| Evidence | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| SHA-256 | `" + EscapeTable(scene?.RawSha256) + "` |");
            sb.AppendLine("| Raw ASCII chars | " + (scene?.RawAsciiText != null ? scene.RawAsciiText.Length.ToString() : "0") + " |");
            sb.AppendLine("| Raw binary bytes | " + (scene?.RawBinaryBytes != null ? scene.RawBinaryBytes.Length.ToString() : "0") + " |");
            sb.AppendLine("| .mb embedded ASCII parsed | " + Bool(scene?.MbEmbeddedAsciiParsed ?? false) + " |");
            sb.AppendLine("| .mb embedded ASCII statements | " + (scene?.MbExtractedAsciiStatementCount ?? 0) + " |");
            sb.AppendLine("| .mb embedded ASCII confidence | " + (scene?.MbExtractedAsciiConfidence ?? 0) + " |");
            sb.AppendLine("| .mb null-terminated statements | " + (scene?.MbNullTerminatedStatementCount ?? 0) + " |");
            sb.AppendLine("| .mb null-terminated score | " + (scene?.MbNullTerminatedScore ?? 0) + " |");
            sb.AppendLine("| .mb chunk placeholders used | " + Bool(scene?.MbUsedChunkPlaceholders ?? false) + " |");
            sb.AppendLine("| .mb string table entries | " + (scene?.MbStringTable?.Count ?? 0) + " |");
            sb.AppendLine("| .mb mesh hints | " + (scene?.MbMeshHints?.Count ?? 0) + " |");
            sb.AppendLine();
        }

        private static void AppendCoverage(StringBuilder sb, MayaSceneData scene)
        {
            int transformLike = CountNodes(scene, IsTransformLike);
            int geometryLike = CountNodes(scene, IsGeometryLike);
            int materialLike = CountNodes(scene, IsMaterialLike);
            int animationLike = CountNodes(scene, IsAnimationLike);
            int rigLike = CountNodes(scene, IsRigLike);
            int constraintLike = CountNodes(scene, IsConstraintLike);
            int unknownLike = CountNodes(scene, IsUnsupportedOrGeneric);

            sb.AppendLine("## 3. Coverage overview");
            sb.AppendLine();
            sb.AppendLine("| Category | Count | Notes |");
            sb.AppendLine("|---|---:|---|");
            sb.AppendLine("| Transform / DAG | " + transformLike + " | transform, joint, DAG-like nodes |");
            sb.AppendLine("| Geometry | " + geometryLike + " | mesh, nurbsCurve, nurbsSurface, shape-like nodes |");
            sb.AppendLine("| Materials / Shading | " + materialLike + " | lambert, phong, blinn, file, shadingEngine, texture-like nodes |");
            sb.AppendLine("| Animation | " + animationLike + " | animCurve / animation-related nodes and commands |");
            sb.AppendLine("| Rig / Deformer | " + rigLike + " | skinCluster, blendShape, cluster, lattice, deformers |");
            sb.AppendLine("| Constraints / IK | " + constraintLike + " | constraint, IK, motion path nodes |");
            sb.AppendLine("| Unsupported / generic risk | " + unknownLike + " | unknown, placeholder, generic, unsupported, evidence-only nodes |");
            sb.AppendLine();
            sb.AppendLine("> Coverage counts are structural. They prove that source data was discovered and preserved, not that every Maya behavior is simulated in Unity.");
            sb.AppendLine();
        }

        private static void AppendNodeTypeBreakdown(StringBuilder sb, MayaSceneData scene, int maxEntries)
        {
            sb.AppendLine("## 4. Node type breakdown");
            sb.AppendLine();
            sb.AppendLine("| Node type | Count |");
            sb.AppendLine("|---|---:|");

            var map = scene?.CountNodeTypes() ?? new Dictionary<string, int>();
            int cap = maxEntries <= 0 ? 256 : maxEntries;
            foreach (var kv in map.OrderByDescending(x => x.Value).ThenBy(x => x.Key, StringComparer.Ordinal).Take(cap))
                sb.AppendLine("| `" + EscapeTable(kv.Key) + "` | " + kv.Value + " |");

            if (map.Count > cap)
                sb.AppendLine("| ... | " + (map.Count - cap) + " more node types omitted | ");

            sb.AppendLine();
        }

        private static void AppendProvenanceBreakdown(StringBuilder sb, MayaSceneData scene)
        {
            sb.AppendLine("## 5. Node provenance breakdown");
            sb.AppendLine();
            sb.AppendLine("| Provenance | Count |");
            sb.AppendLine("|---|---:|");

            var map = new Dictionary<MayaNodeProvenance, int>();
            if (scene?.Nodes != null)
            {
                foreach (var n in scene.Nodes.Values)
                {
                    var p = n != null ? n.Provenance : MayaNodeProvenance.Unknown;
                    map.TryGetValue(p, out int c);
                    map[p] = c + 1;
                }
            }

            foreach (MayaNodeProvenance p in Enum.GetValues(typeof(MayaNodeProvenance)))
            {
                map.TryGetValue(p, out int c);
                sb.AppendLine("| " + p + " | " + c + " |");
            }
            sb.AppendLine();
        }

        private static void AppendUnsupportedNodes(StringBuilder sb, MayaSceneData scene, int maxEntries)
        {
            sb.AppendLine("## 6. Unsupported / generic-risk nodes");
            sb.AppendLine();
            sb.AppendLine("These nodes should be reviewed when deciding whether an import is production-ready.");
            sb.AppendLine();
            sb.AppendLine("| Node | Type | Provenance |");
            sb.AppendLine("|---|---|---|");

            int cap = maxEntries <= 0 ? 256 : maxEntries;
            int count = 0;
            if (scene?.Nodes != null)
            {
                foreach (var n in scene.Nodes.Values
                    .Where(IsUnsupportedOrGeneric)
                    .OrderBy(x => x.NodeType ?? "", StringComparer.Ordinal)
                    .ThenBy(x => x.Name ?? "", StringComparer.Ordinal))
                {
                    if (count >= cap) break;
                    sb.AppendLine("| `" + EscapeTable(n.Name) + "` | `" + EscapeTable(n.NodeType) + "` | " + n.Provenance + " |");
                    count++;
                }
            }

            if (count == 0) sb.AppendLine("| - | - | - |");
            sb.AppendLine();
        }

        private static void AppendStructuredCommandCounts(StringBuilder sb, MayaSceneData scene)
        {
            sb.AppendLine("## 7. Structured command counts");
            sb.AppendLine();
            sb.AppendLine("| Command / data | Count |");
            sb.AppendLine("|---|---:|");
            sb.AppendLine("| fileInfo | " + (scene?.FileInfo?.Count ?? 0) + " |");
            sb.AppendLine("| requires | " + (scene?.Requires?.Count ?? 0) + " |");
            sb.AppendLine("| workspace rules | " + (scene?.WorkspaceRules?.Count ?? 0) + " |");
            sb.AppendLine("| namespace ops | " + (scene?.NamespaceOps?.Count ?? 0) + " |");
            sb.AppendLine("| setKeyframe | " + (scene?.SetKeyframes?.Count ?? 0) + " |");
            sb.AppendLine("| setDrivenKeyframe | " + (scene?.DrivenKeyframes?.Count ?? 0) + " |");
            sb.AppendLine("| animLayer | " + (scene?.AnimLayers?.Count ?? 0) + " |");
            sb.AppendLine("| connectDynamic | " + (scene?.ConnectDynamics?.Count ?? 0) + " |");
            sb.AppendLine("| scriptNode | " + (scene?.ScriptNodes?.Count ?? 0) + " |");
            sb.AppendLine("| evalDeferred | " + (scene?.EvalDeferred?.Count ?? 0) + " |");
            sb.AppendLine("| expression | " + (scene?.Expressions?.Count ?? 0) + " |");
            sb.AppendLine();
        }

        private static void AppendLog(StringBuilder sb, MayaImportLog log)
        {
            sb.AppendLine("## 8. Import log");
            sb.AppendLine();
            AppendLogList(sb, "Errors", log?.Errors);
            AppendLogList(sb, "Warnings", log?.Warnings);
            AppendLogList(sb, "Infos", log?.Infos);
        }

        private static void AppendLogList(StringBuilder sb, string title, List<string> items)
        {
            sb.AppendLine("### " + title);
            sb.AppendLine();
            if (items == null || items.Count == 0)
            {
                sb.AppendLine("- None");
                sb.AppendLine();
                return;
            }

            foreach (var item in items.Take(512))
                sb.AppendLine("- " + EscapeMarkdown(item));
            if (items.Count > 512) sb.AppendLine("- ... " + (items.Count - 512) + " more omitted");
            sb.AppendLine();
        }

        private static void AppendValidationChecklist(StringBuilder sb, MayaSceneData scene)
        {
            sb.AppendLine("## 9. Validation checklist");
            sb.AppendLine();
            sb.AppendLine("| Check | Result |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Source hash exists | " + Pass(!string.IsNullOrEmpty(scene?.RawSha256)) + " |");
            sb.AppendLine("| Nodes discovered | " + Pass((scene?.Nodes?.Count ?? 0) > 0) + " |");
            sb.AppendLine("| Connections discovered | " + Pass((scene?.Connections?.Count ?? 0) > 0) + " |");
            sb.AppendLine("| Has transform-like nodes | " + Pass(CountNodes(scene, IsTransformLike) > 0) + " |");
            sb.AppendLine("| Has geometry-like nodes | " + Pass(CountNodes(scene, IsGeometryLike) > 0) + " |");
            sb.AppendLine("| Has material-like nodes | " + Pass(CountNodes(scene, IsMaterialLike) > 0) + " |");
            sb.AppendLine("| Unsupported/generic nodes need review | " + (((CountNodes(scene, IsUnsupportedOrGeneric) > 0) ? "Review required" : "No obvious generic-risk nodes")) + " |");
            sb.AppendLine();
        }

        private static void AppendDisclaimer(StringBuilder sb)
        {
            sb.AppendLine("## 10. Interpretation");
            sb.AppendLine();
            sb.AppendLine("This report separates **source discovery** from **Unity behavior parity**.");
            sb.AppendLine();
            sb.AppendLine("- A node listed in this report means the importer discovered and preserved source evidence for it.");
            sb.AppendLine("- A reconstructed Unity object means the builder created an inspectable GameObject/component representation.");
            sb.AppendLine("- Full Maya runtime behavior, shader parity, rig evaluation, deformer evaluation, and plugin-specific behavior require explicit validation per sample scene.");
            sb.AppendLine();
        }

        private static int CountNodes(MayaSceneData scene, Func<NodeRecord, bool> predicate)
        {
            if (scene?.Nodes == null || predicate == null) return 0;
            int count = 0;
            foreach (var n in scene.Nodes.Values)
                if (n != null && predicate(n)) count++;
            return count;
        }

        private static bool IsTransformLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return Eq(t, "transform") || Eq(t, "joint") || (n?.Name ?? "").Contains("|");
        }

        private static bool IsGeometryLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return Eq(t, "mesh") || Eq(t, "nurbsCurve") || Eq(t, "nurbsSurface") || Contains(t, "shape") || Contains(t, "geometry");
        }

        private static bool IsMaterialLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return Eq(t, "shadingEngine") || Eq(t, "lambert") || Eq(t, "phong") || Eq(t, "blinn") || Eq(t, "file") || Contains(t, "shader") || Contains(t, "texture") || Contains(t, "surface") || Contains(t, "bump") || Contains(t, "ramp") || Contains(t, "remap");
        }

        private static bool IsAnimationLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return t.StartsWith("animCurve", StringComparison.OrdinalIgnoreCase) || Contains(t, "anim");
        }

        private static bool IsRigLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return Eq(t, "skinCluster") || Eq(t, "blendShape") || Eq(t, "cluster") || Eq(t, "lattice") || Contains(t, "deformer") || Contains(t, "joint");
        }

        private static bool IsConstraintLike(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            return Contains(t, "constraint") || Contains(t, "ik") || Contains(t, "motionPath");
        }

        private static bool IsUnsupportedOrGeneric(NodeRecord n)
        {
            string t = n?.NodeType ?? "";
            if (string.IsNullOrEmpty(t)) return true;
            if (Eq(t, "unknown") || Eq(t, "unknownType")) return true;
            if (Contains(t, "placeholder")) return true;
            if (n != null && (n.Provenance == MayaNodeProvenance.MbChunkPlaceholder || n.Provenance == MayaNodeProvenance.MbHeuristic)) return true;
            return false;
        }

        private static string ResolveReportFolder(string configured)
        {
            if (string.IsNullOrEmpty(configured)) configured = "Assets/MayaImported/Reports";
            configured = configured.Replace('\\', '/');
            if (Path.IsPathRooted(configured)) return configured;
            return Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), configured));
        }

        private static string MakeSafeFileName(string s)
        {
            if (string.IsNullOrEmpty(s)) return "MayaScene";
            foreach (char c in Path.GetInvalidFileNameChars()) s = s.Replace(c, '_');
            return s.Replace(' ', '_');
        }

        private static bool Eq(string a, string b) => string.Equals(a, b, StringComparison.OrdinalIgnoreCase);
        private static bool Contains(string a, string b) => !string.IsNullOrEmpty(a) && a.IndexOf(b, StringComparison.OrdinalIgnoreCase) >= 0;
        private static string Bool(bool v) => v ? "Yes" : "No";
        private static string Pass(bool v) => v ? "Pass" : "Fail";

        private static string EscapeTable(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
        }

        private static string EscapeMarkdown(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("\r", " ").Replace("\n", " ");
        }
    }
}
