// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorProfile
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorProfile")]
    public sealed class MayaGenerated_ColorProfileNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorProfile)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string inputProfile;
        [SerializeField] private string outputProfile;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            inputProfile = ReadString("", ".inputProfile", "inputProfile", ".inProfile", "inProfile", ".sourceProfile", "sourceProfile");
            outputProfile = ReadString("", ".outputProfile", "outputProfile", ".outProfile", "outProfile", ".destProfile", "destProfile");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, inputProfile='{inputProfile}', outputProfile='{outputProfile}' (no color conversion executed)");
        }
    }
}
