// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: arcLengthDimension
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("arcLengthDimension")]
    public sealed class MayaGenerated_ArcLengthDimensionNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float arcLength;
        [SerializeField] private string inputIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            arcLength = ReadFloat(0f, ".arcLength", "arcLength", ".al", "al", ".value", "value");
            inputIncomingPlug = FindLastIncomingTo("input", "in", "i", "curve", "crv");

            SetNotes($"{NodeType} '{NodeName}' decoded: arcLength={arcLength}, incoming={(string.IsNullOrEmpty(inputIncomingPlug) ? "none" : inputIncomingPlug)}");
        }
    }
}
