// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: avgNurbsSurfacePoints
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("avgNurbsSurfacePoints")]
    public sealed class MayaGenerated_AvgNurbsSurfacePointsNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private int pointCountHint;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            pointCountHint = ReadInt(0, ".pointCount", "pointCount", ".n", "n");
            incomingPlug = FindLastIncomingTo("inputSurface", "is", "input", "in");
            SetNotes($"{NodeType} '{NodeName}' decoded: pointCountHint={pointCountHint}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
