// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bezierCurve
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bezierCurve")]
    public sealed class MayaGenerated_BezierCurveNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bezierCurve)")]
        [SerializeField] private int degree;
        [SerializeField] private bool periodic;
        [SerializeField] private string incomingControlPoints;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            degree = ReadInt(3, ".degree", "degree", ".deg", "deg");
            periodic = ReadBool(false, ".periodic", "periodic", ".form", "form", ".closed", "closed");

            incomingControlPoints = FindLastIncomingTo("controlPoints", "cp", "create", "input");

            SetNotes($"{NodeType} '{NodeName}' decoded: degree={degree}, periodic={periodic}, incomingCP={(string.IsNullOrEmpty(incomingControlPoints) ? "none" : incomingControlPoints)}");
        }
    }
}
