// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletSolverShape
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletSolverShape")]
    public sealed class MayaGenerated_BulletSolverShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletSolverShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int subSteps = 1;
        [SerializeField] private Vector3 gravity = new Vector3(0, -9.8f, 0);

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            subSteps = ReadInt(1, ".subSteps", "subSteps", ".ss", "ss");

            float gx = ReadFloat(0f, ".gravityX", "gravityX", ".gx", "gx");
            float gy = ReadFloat(-9.8f, ".gravityY", "gravityY", ".gy", "gy");
            float gz = ReadFloat(0f, ".gravityZ", "gravityZ", ".gz", "gz");
            gravity = new Vector3(gx, gy, gz);

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, subSteps={subSteps}, gravity={gravity} (no runtime bullet sim; attrs+connections preserved)");
        }
    }
}
