// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bump3d
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bump3d")]
    public sealed class MayaGenerated_Bump3dNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bump3d)")]
        [SerializeField] private float bumpDepth = 1f;
        [SerializeField] private int bumpInterp;
        [SerializeField] private string incomingBumpValue;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bumpDepth = ReadFloat(1f, ".bumpDepth", "bumpDepth", ".bd", "bd", ".depth", "depth");
            bumpInterp = ReadInt(0, ".bumpInterp", "bumpInterp", ".interp", "interp");

            incomingBumpValue = FindLastIncomingTo("bumpValue", "bv", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: bumpDepth={bumpDepth}, interp={bumpInterp}, incomingBump={(string.IsNullOrEmpty(incomingBumpValue) ? "none" : incomingBumpValue)} (shader eval not simulated)");
        }
    }
}
