// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorCorrect
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorCorrect")]
    public sealed class MayaGenerated_ColorCorrectNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorCorrect)")]
        [SerializeField] private bool enabled = true;

        [SerializeField] private float gamma = 1f;
        [SerializeField] private float gain = 1f;
        [SerializeField] private float offset;
        [SerializeField] private float saturation = 1f;

        [SerializeField] private string incomingColor;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            gamma = ReadFloat(1f, ".gamma", "gamma", ".gma", "gma");
            gain = ReadFloat(1f, ".gain", "gain", ".g", "g");
            offset = ReadFloat(0f, ".offset", "offset", ".o", "o");
            saturation = ReadFloat(1f, ".saturation", "saturation", ".sat", "sat");

            incomingColor = FindLastIncomingTo("inputColor", "inColor", "color", "c");
            string ic = string.IsNullOrEmpty(incomingColor) ? "none" : incomingColor;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, gamma={gamma}, gain={gain}, offset={offset}, sat={saturation}, incomingColor={ic} (shader eval not simulated)");
        }
    }
}
