// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorConstant
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorConstant")]
    public sealed class MayaGenerated_ColorConstantNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorConstant)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private Color color = Color.white;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            float r = ReadFloat(1f, ".colorR", "colorR", ".r", "r", ".outColorR", "outColorR");
            float g = ReadFloat(1f, ".colorG", "colorG", ".g", "g", ".outColorG", "outColorG");
            float b = ReadFloat(1f, ".colorB", "colorB", ".b", "b", ".outColorB", "outColorB");
            float a = ReadFloat(1f, ".colorA", "colorA", ".a", "a", ".outAlpha", "outAlpha");
            color = new Color(r, g, b, a);

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, color={color} (constant)");
        }
    }
}
