// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: ballProjManip
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("ballProjManip")]
    public sealed class MayaGenerated_BallProjManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (ballProjManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float size;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            size = ReadFloat(0f, ".size", "size", ".radius", "radius", ".s", "s");
            incomingPlug = FindLastIncomingTo("input", "in", "i");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, size={size}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
