// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletSoftConstraintShape
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletSoftConstraintShape")]
    public sealed class MayaGenerated_BulletSoftConstraintShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletSoftConstraintShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int constraintType;
        [SerializeField] private float strength;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            constraintType = ReadInt(0, ".constraintType", "constraintType", ".type", "type");
            strength = ReadFloat(0f, ".strength", "strength", ".s", "s");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, type={constraintType}, strength={strength} (no runtime constraint solve; attrs+connections preserved)");
        }
    }
}
