// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletRigidCollection
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletRigidCollection")]
    public sealed class MayaGenerated_BulletRigidCollectionNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletRigidCollection)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int memberCountHint;
        [SerializeField] private float solverScale = 1f;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            memberCountHint = ReadInt(0, ".memberCount", "memberCount", ".count", "count");
            solverScale = ReadFloat(1f, ".solverScale", "solverScale", ".scale", "scale", ".s", "s");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, memberCountHint={memberCountHint}, solverScale={solverScale} (collection membership via connections preserved)");
        }
    }
}
