// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bevelManip
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bevelManip")]
    public sealed class MayaGenerated_BevelManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bevelManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float size;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            size = ReadFloat(0f, ".size", "size", ".s", "s");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, size={size}");
        }
    }
}
