// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: assemblyReference
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("assemblyReference")]
    public sealed class MayaGenerated_AssemblyReferenceNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private string referenceTarget;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            referenceTarget = ReadString("", ".referenceTarget", "referenceTarget", ".target", "target", ".path", "path");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, target='{referenceTarget}'");
        }
    }
}
