// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyRel2FloatsOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyRel2FloatsOverride")]
    public sealed class MayaGenerated_ApplyRel2FloatsOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float x;
        [SerializeField] private float y;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            x = ReadFloat(0f, ".x", "x", ".valueX", "valueX");
            y = ReadFloat(0f, ".y", "y", ".valueY", "valueY");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, (x,y)=({x},{y})");
        }
    }
}
