// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: atanDL
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("atanDL")]
    public sealed class MayaGenerated_AtanDLNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float input;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            input = ReadFloat(0f, ".input", "input", ".in", "in", ".value", "value");
            incomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");
            SetNotes($"{NodeType} '{NodeName}' decoded: input={input}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
