// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorCondition
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorCondition")]
    public sealed class MayaGenerated_ColorConditionNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorCondition)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int operation;
        [SerializeField] private float firstTerm;
        [SerializeField] private float secondTerm;

        [SerializeField] private Color colorIfTrue = Color.white;
        [SerializeField] private Color colorIfFalse = Color.black;

        [SerializeField] private string incomingFirst;
        [SerializeField] private string incomingSecond;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            operation = ReadInt(0, ".operation", "operation", ".op", "op", ".condition", "condition");
            firstTerm = ReadFloat(0f, ".firstTerm", "firstTerm", ".ft", "ft", ".input1", "input1");
            secondTerm = ReadFloat(0f, ".secondTerm", "secondTerm", ".st", "st", ".input2", "input2");

            float tr = ReadFloat(1f, ".colorIfTrueR", "colorIfTrueR", ".ctr", "ctr");
            float tg = ReadFloat(1f, ".colorIfTrueG", "colorIfTrueG", ".ctg", "ctg");
            float tb = ReadFloat(1f, ".colorIfTrueB", "colorIfTrueB", ".ctb", "ctb");
            float ta = ReadFloat(1f, ".colorIfTrueA", "colorIfTrueA", ".cta", "cta");
            colorIfTrue = new Color(tr, tg, tb, ta);

            float fr = ReadFloat(0f, ".colorIfFalseR", "colorIfFalseR", ".cfr", "cfr");
            float fg = ReadFloat(0f, ".colorIfFalseG", "colorIfFalseG", ".cfg", "cfg");
            float fb = ReadFloat(0f, ".colorIfFalseB", "colorIfFalseB", ".cfb", "cfb");
            float fa = ReadFloat(1f, ".colorIfFalseA", "colorIfFalseA", ".cfa", "cfa");
            colorIfFalse = new Color(fr, fg, fb, fa);

            incomingFirst = FindLastIncomingTo("firstTerm", "ft", "input1");
            incomingSecond = FindLastIncomingTo("secondTerm", "st", "input2");

            string i1 = string.IsNullOrEmpty(incomingFirst) ? "none" : incomingFirst;
            string i2 = string.IsNullOrEmpty(incomingSecond) ? "none" : incomingSecond;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, op={operation}, first={firstTerm}, second={secondTerm}, incomingFirst={i1}, incomingSecond={i2} (shader eval not simulated)");
        }
    }
}
