// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: barnDoorManip
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("barnDoorManip")]
    public sealed class MayaGenerated_BarnDoorManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (barnDoorManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float width;
        [SerializeField] private float height;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            width = ReadFloat(0f, ".width", "width", ".w", "w");
            height = ReadFloat(0f, ".height", "height", ".h", "h");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, width={width}, height={height}");
        }
    }
}
