// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorLogic
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorLogic")]
    public sealed class MayaGenerated_ColorLogicNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorLogic)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int operation;

        [SerializeField] private string incomingA;
        [SerializeField] private string incomingB;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            operation = ReadInt(0, ".operation", "operation", ".op", "op", ".mode", "mode");

            incomingA = FindLastIncomingTo("colorA", "a", "inputA", "inA");
            incomingB = FindLastIncomingTo("colorB", "b", "inputB", "inB");

            string ia = string.IsNullOrEmpty(incomingA) ? "none" : incomingA;
            string ib = string.IsNullOrEmpty(incomingB) ? "none" : incomingB;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, op={operation}, incomingA={ia}, incomingB={ib} (shader eval not simulated)");
        }
    }
}
