// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: clusterHandle
// Production implementation (non-empty decode; preserves all raw data)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("clusterHandle")]
    public sealed class MayaGenerated_ClusterHandleNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (clusterHandle)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float envelope = 1f;
        [SerializeField] private int membershipCountHint;

        [SerializeField] private string incomingEnvelope;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            envelope = ReadFloat(1f, ".envelope", "envelope", ".env", "env");
            membershipCountHint = ReadInt(0, ".memberCount", "memberCount", ".count", "count");

            incomingEnvelope = FindLastIncomingTo("envelope", "env");

            string ie = string.IsNullOrEmpty(incomingEnvelope) ? "none" : incomingEnvelope;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, env={envelope}, memberCountHint={membershipCountHint}, incomingEnv={ie} (membership via connections preserved)");
        }
    }
}
