// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bevelPlus
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bevelPlus")]
    public sealed class MayaGenerated_BevelPlusNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bevelPlus)")]
        [SerializeField] private float offset;
        [SerializeField] private int segments;
        [SerializeField] private float rounding;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            offset = ReadFloat(0f, ".offset", "offset", ".width", "width", ".w", "w");
            segments = ReadInt(0, ".segments", "segments", ".divisions", "divisions");
            rounding = ReadFloat(0f, ".rounding", "rounding", ".r", "r");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, offset={offset}, segments={segments}, rounding={rounding}");
        }
    }
}
