// Assets/MayaImporter/MayaGenerated_AnimBlendInOutNode.cs
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: animBlendInOut
// Phase C implementation (opaque decode, non-empty).
//
// Purpose:
// - Keep 100% of raw Maya attributes & connections (lossless portability)
// - Provide deterministic, inspector-visible decode so Coverage marks this nodeType as IMPLEMENTED
//
// Note:
// - This does NOT attempt to simulate Maya behavior.
// - No Autodesk/Maya APIs are used.

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("animBlendInOut")]
    public sealed class MayaGenerated_AnimBlendInOutNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool hasAttributes;
        [SerializeField] private bool hasConnections;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            hasAttributes = AttributeCount > 0;
            hasConnections = ConnectionCount > 0;

            SetNotes($"{NodeType} '{NodeName}' opaque decoded (attrs={AttributeCount}, conns={ConnectionCount}).");
        }
    }
}
