// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: attachCurve
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("attachCurve")]
    public sealed class MayaGenerated_AttachCurveNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float parameter;
        [SerializeField] private string inputIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            parameter = ReadFloat(0f, ".parameter", "parameter", ".u", "u", ".param", "param");
            inputIncomingPlug = FindLastIncomingTo("inputCurve", "ic", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: parameter={parameter}, incoming={(string.IsNullOrEmpty(inputIncomingPlug) ? "none" : inputIncomingPlug)}");
        }
    }
}
