// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: audio
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("audio")]
    public sealed class MayaGenerated_AudioNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private string filePath;
        [SerializeField] private float offset;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            filePath = ReadString("", ".filename", "filename", ".fileName", "fileName", ".path", "path");
            offset = ReadFloat(0f, ".offset", "offset", ".startFrame", "startFrame", ".startTime", "startTime");
            SetNotes($"{NodeType} '{NodeName}' decoded: file='{filePath}', offset={offset}");
        }
    }
}
