// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletRigidBodyConstraintShape
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletRigidBodyConstraintShape")]
    public sealed class MayaGenerated_BulletRigidBodyConstraintShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletRigidBodyConstraintShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int constraintType;
        [SerializeField] private float breakForce;
        [SerializeField] private float breakTorque;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            constraintType = ReadInt(0, ".constraintType", "constraintType", ".type", "type");
            breakForce = ReadFloat(0f, ".breakForce", "breakForce", ".bf", "bf");
            breakTorque = ReadFloat(0f, ".breakTorque", "breakTorque", ".bt", "bt");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, type={constraintType}, breakForce={breakForce}, breakTorque={breakTorque} (no runtime constraint solve; attrs+connections preserved)");
        }
    }
}
