// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletRigidSet
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletRigidSet")]
    public sealed class MayaGenerated_BulletRigidSetNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletRigidSet)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int memberCountHint;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            memberCountHint = ReadInt(0, ".memberCount", "memberCount", ".count", "count");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, memberCountHint={memberCountHint} (membership via connections preserved)");
        }
    }
}
