// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: arubaTessellate
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("arubaTessellate")]
    public sealed class MayaGenerated_ArubaTessellateNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private int tessellationLevel;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            tessellationLevel = ReadInt(0, ".tessellationLevel", "tessellationLevel", ".level", "level", ".tl", "tl");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, tessellationLevel={tessellationLevel}");
        }
    }
}
