// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blindDataTemplate
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blindDataTemplate")]
    public sealed class MayaGenerated_BlindDataTemplateNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blindDataTemplate)")]
        [SerializeField] private int templateId;
        [SerializeField] private string templateName;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            templateId = ReadInt(0, ".templateId", "templateId", ".id", "id");
            templateName = ReadString("", ".templateName", "templateName", ".name", "name");

            SetNotes($"{NodeType} '{NodeName}' decoded: templateId={templateId}, templateName='{templateName}' (opaque)");
        }
    }
}
