// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: computeGlobal (+ alias: ComputeGlobal)
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("computeGlobal")]
    [MayaNodeType("ComputeGlobal")] // Maya2026 standard list alias
    public sealed class MayaGenerated_ComputeGlobalNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (computeGlobal / ComputeGlobal)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string expression;
        [SerializeField] private int mode;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            expression = ReadString("", ".expression", "expression", ".expr", "expr", ".code", "code");
            mode = ReadInt(0, ".mode", "mode");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mode={mode}, expression='{expression}' (not executed; stored for reconstruction)");
        }
    }
}
