// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyRelOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyRelOverride")]
    public sealed class MayaGenerated_ApplyRelOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string mode;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            mode = ReadString("", ".mode", "mode", ".operation", "operation");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mode='{mode}'");
        }
    }
}
