// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyRelFloatOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyRelFloatOverride")]
    public sealed class MayaGenerated_ApplyRelFloatOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float value;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            value = ReadFloat(0f, ".value", "value", ".v", "v");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, value={value}");
        }
    }
}
