// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: avgCurves
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("avgCurves")]
    public sealed class MayaGenerated_AvgCurvesNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float weight;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            weight = ReadFloat(1f, ".weight", "weight", ".w", "w");
            incomingPlug = FindLastIncomingTo("input", "in", "i");
            SetNotes($"{NodeType} '{NodeName}' decoded: weight={weight}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
