// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletInitialState
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletInitialState")]
    public sealed class MayaGenerated_BulletInitialStateNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletInitialState)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private bool useInitialVelocity;
        [SerializeField] private Vector3 initialVelocity;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            useInitialVelocity = ReadBool(false, ".useInitialVelocity", "useInitialVelocity", ".uiv", "uiv");
            float vx = ReadFloat(0f, ".initialVelocityX", "initialVelocityX", ".vx", "vx");
            float vy = ReadFloat(0f, ".initialVelocityY", "initialVelocityY", ".vy", "vy");
            float vz = ReadFloat(0f, ".initialVelocityZ", "initialVelocityZ", ".vz", "vz");
            initialVelocity = new Vector3(vx, vy, vz);

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, useInitialVelocity={useInitialVelocity}, v0={initialVelocity} (no runtime bullet sim; attrs+connections preserved)");
        }
    }
}
