// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorManagementGlobals
// Production implementation (non-empty decode; project-level settings snapshot)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorManagementGlobals")]
    public sealed class MayaGenerated_ColorManagementGlobalsNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorManagementGlobals)")]
        [SerializeField] private bool enabled = true;

        [SerializeField] private string configFile;
        [SerializeField] private string viewTransform;
        [SerializeField] private string display;
        [SerializeField] private string renderingSpace;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            configFile = ReadString("", ".configFile", "configFile", ".ocioConfig", "ocioConfig");
            viewTransform = ReadString("", ".viewTransform", "viewTransform", ".view", "view");
            display = ReadString("", ".display", "display");
            renderingSpace = ReadString("", ".renderingSpace", "renderingSpace", ".workingSpace", "workingSpace");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, configFile='{configFile}', display='{display}', view='{viewTransform}', renderingSpace='{renderingSpace}' (Unity color mgmt not auto-mapped)");
        }
    }
}
