// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: brush
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("brush")]
    public sealed class MayaGenerated_BrushNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (brush)")]
        [SerializeField] private float radius = 1f;
        [SerializeField] private float strength = 1f;
        [SerializeField] private float falloff;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            radius = ReadFloat(1f, ".radius", "radius", ".r", "r", ".size", "size");
            strength = ReadFloat(1f, ".strength", "strength", ".s", "s", ".opacity", "opacity");
            falloff = ReadFloat(0f, ".falloff", "falloff", ".f", "f");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, radius={radius}, strength={strength}, falloff={falloff} (no paint sim; attrs+connections preserved)");
        }
    }
}
