// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: componentFalloff
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("componentFalloff")]
    public sealed class MayaGenerated_ComponentFalloffNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (componentFalloff)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int falloffType;
        [SerializeField] private float radius = 1f;
        [SerializeField] private float weight = 1f;

        [SerializeField] private string incomingCenter;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            falloffType = ReadInt(0, ".falloffType", "falloffType", ".type", "type");
            radius = ReadFloat(1f, ".radius", "radius", ".r", "r");
            weight = ReadFloat(1f, ".weight", "weight", ".w", "w");

            incomingCenter = FindLastIncomingTo("center", "centerX", "centerY", "centerZ");
            string ic = string.IsNullOrEmpty(incomingCenter) ? "none" : incomingCenter;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, type={falloffType}, radius={radius}, weight={weight}, incomingCenter={ic}");
        }
    }
}
