// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bluePencil
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bluePencil")]
    public sealed class MayaGenerated_BluePencilNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bluePencil)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float opacity = 1f;
        [SerializeField] private int layerIndex;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            opacity = ReadFloat(1f, ".opacity", "opacity", ".alpha", "alpha", ".a", "a");
            layerIndex = ReadInt(0, ".layer", "layer", ".layerIndex", "layerIndex");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, opacity={opacity}, layerIndex={layerIndex} (no drawing playback; attrs+connections preserved)");
        }
    }
}
