// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorMask
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorMask")]
    public sealed class MayaGenerated_ColorMaskNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorMask)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private Color mask = new Color(1, 1, 1, 1);

        [SerializeField] private string incomingColor;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            float r = ReadFloat(1f, ".maskR", "maskR", ".r", "r");
            float g = ReadFloat(1f, ".maskG", "maskG", ".g", "g");
            float b = ReadFloat(1f, ".maskB", "maskB", ".b", "b");
            float a = ReadFloat(1f, ".maskA", "maskA", ".a", "a");
            mask = new Color(r, g, b, a);

            incomingColor = FindLastIncomingTo("inputColor", "inColor", "color", "c");
            string ic = string.IsNullOrEmpty(incomingColor) ? "none" : incomingColor;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mask={mask}, incomingColor={ic} (shader eval not simulated)");
        }
    }
}
