// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: clusterFlexorShape
// Phase C implementation (non-empty decode; keeps raw attrs+connections)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("clusterFlexorShape")]
    public sealed class MayaGenerated_ClusterFlexorShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (clusterFlexorShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float envelope = 1f;
        [SerializeField] private float stiffness;
        [SerializeField] private float damping;

        [SerializeField] private string incomingGeometry;
        [SerializeField] private string incomingEnvelope;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            envelope = ReadFloat(1f, ".envelope", "envelope", ".env", "env");
            stiffness = ReadFloat(0f, ".stiffness", "stiffness", ".k", "k");
            damping = ReadFloat(0f, ".damping", "damping", ".dmp", "dmp");

            incomingGeometry = FindLastIncomingTo("inputGeometry", "inputGeom", "input", "in");
            incomingEnvelope = FindLastIncomingTo("envelope", "env");

            string ig = string.IsNullOrEmpty(incomingGeometry) ? "none" : incomingGeometry;
            string ie = string.IsNullOrEmpty(incomingEnvelope) ? "none" : incomingEnvelope;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, env={envelope}, stiffness={stiffness}, damping={damping}, incomingGeom={ig}, incomingEnv={ie}");
        }
    }
}
