// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: audioWave
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("audioWave")]
    public sealed class MayaGenerated_AudioWaveNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float amplitude;
        [SerializeField] private float time;
        [SerializeField] private string incomingTimePlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            amplitude = ReadFloat(0f, ".amplitude", "amplitude", ".amp", "amp");
            time = ReadFloat(0f, ".time", "time", ".t", "t");
            incomingTimePlug = FindLastIncomingTo("time", "t");

            SetNotes($"{NodeType} '{NodeName}' decoded: amp={amplitude}, time={time}, incomingTime={(string.IsNullOrEmpty(incomingTimePlug) ? "none" : incomingTimePlug)}");
        }
    }
}
