// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: attrHierarchyTest
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("attrHierarchyTest")]
    public sealed class MayaGenerated_AttrHierarchyTestNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private int testMode;
        [SerializeField] private string info;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            testMode = ReadInt(0, ".mode", "mode", ".testMode", "testMode");
            info = ReadString("", ".info", "info", ".name", "name");
            SetNotes($"{NodeType} '{NodeName}' decoded: testMode={testMode}, info='{info}'");
        }
    }
}
