// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: colorComposite
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("colorComposite")]
    public sealed class MayaGenerated_ColorCompositeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (colorComposite)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int operation;
        [SerializeField] private float factor = 1f;
        [SerializeField] private Color colorA = Color.white;
        [SerializeField] private Color colorB = Color.black;

        [SerializeField] private string incomingA;
        [SerializeField] private string incomingB;
        [SerializeField] private string incomingFactor;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            operation = ReadInt(0, ".operation", "operation", ".op", "op", ".mode", "mode");
            factor = ReadFloat(1f, ".factor", "factor", ".f", "f", ".alpha", "alpha", ".a", "a");

            float ar = ReadFloat(1f, ".colorAR", "colorAR", ".aR", "aR", ".colorA.r", "colorA.r");
            float ag = ReadFloat(1f, ".colorAG", "colorAG", ".aG", "aG", ".colorA.g", "colorA.g");
            float ab = ReadFloat(1f, ".colorAB", "colorAB", ".aB", "aB", ".colorA.b", "colorA.b");
            float aa = ReadFloat(1f, ".colorAA", "colorAA", ".aA", "aA", ".colorA.a", "colorA.a");
            colorA = new Color(ar, ag, ab, aa);

            float br = ReadFloat(0f, ".colorBR", "colorBR", ".bR", "bR", ".colorB.r", "colorB.r");
            float bg = ReadFloat(0f, ".colorBG", "colorBG", ".bG", "bG", ".colorB.g", "colorB.g");
            float bb = ReadFloat(0f, ".colorBB", "colorBB", ".bB", "bB", ".colorB.b", "colorB.b");
            float ba = ReadFloat(1f, ".colorBA", "colorBA", ".bA", "bA", ".colorB.a", "colorB.a");
            colorB = new Color(br, bg, bb, ba);

            incomingA = FindLastIncomingTo("colorA", "a", "colorAR", "aR");
            incomingB = FindLastIncomingTo("colorB", "b", "colorBR", "bR");
            incomingFactor = FindLastIncomingTo("factor", "f", "alpha", "a");

            string ia = string.IsNullOrEmpty(incomingA) ? "none" : incomingA;
            string ib = string.IsNullOrEmpty(incomingB) ? "none" : incomingB;
            string ifa = string.IsNullOrEmpty(incomingFactor) ? "none" : incomingFactor;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, op={operation}, factor={factor}, incomingA={ia}, incomingB={ib}, incomingFactor={ifa} (shader eval not simulated)");
        }
    }
}
