// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyAbsOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyAbsOverride")]
    public sealed class MayaGenerated_ApplyAbsOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string mode;
        [SerializeField] private string sampleIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            mode = ReadString("", ".mode", "mode", ".operation", "operation");
            sampleIncomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mode='{mode}', incoming={(string.IsNullOrEmpty(sampleIncomingPlug) ? "none" : sampleIncomingPlug)}");
        }
    }
}
