// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyConnectionOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyConnectionOverride")]
    public sealed class MayaGenerated_ApplyConnectionOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string targetPlug;
        [SerializeField] private string sampleIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            targetPlug = ReadString("", ".targetPlug", "targetPlug", ".dst", "dst", ".destination", "destination");
            sampleIncomingPlug = FindLastIncomingTo("input", "in", "i", "source", "src");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, targetPlug='{targetPlug}', incoming={(string.IsNullOrEmpty(sampleIncomingPlug) ? "none" : sampleIncomingPlug)}");
        }
    }
}
