// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blendColorSets
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blendColorSets")]
    public sealed class MayaGenerated_BlendColorSetsNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blendColorSets)")]
        [SerializeField] private float weight = 1f;
        [SerializeField] private bool normalize;
        [SerializeField] private string incomingWeight;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            weight = ReadFloat(1f, ".weight", "weight", ".w", "w", ".blend", "blend");
            normalize = ReadBool(false, ".normalize", "normalize", ".nrm", "nrm");

            incomingWeight = FindLastIncomingTo("weight", "w");

            SetNotes($"{NodeType} '{NodeName}' decoded: weight={weight}, normalize={normalize}, incomingWeight={(string.IsNullOrEmpty(incomingWeight) ? "none" : incomingWeight)}");
        }
    }
}
