// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: atan2
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("atan2")]
    public sealed class MayaGenerated_Atan2Node : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private float y;
        [SerializeField] private float x;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            y = ReadFloat(0f, ".inputY", "inputY", ".y", "y");
            x = ReadFloat(0f, ".inputX", "inputX", ".x", "x");
            SetNotes($"{NodeType} '{NodeName}' decoded: (y,x)=({y},{x})");
        }
    }
}
