// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: componentMatch
// Phase C implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("componentMatch")]
    public sealed class MayaGenerated_ComponentMatchNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (componentMatch)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int matchMode;
        [SerializeField] private float tolerance;

        [SerializeField] private string incomingSource;
        [SerializeField] private string incomingTarget;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            matchMode = ReadInt(0, ".matchMode", "matchMode", ".mode", "mode");
            tolerance = ReadFloat(0f, ".tolerance", "tolerance", ".tol", "tol");

            incomingSource = FindLastIncomingTo("source", "src", "inputA", "inA");
            incomingTarget = FindLastIncomingTo("target", "dst", "inputB", "inB");

            string isrc = string.IsNullOrEmpty(incomingSource) ? "none" : incomingSource;
            string idst = string.IsNullOrEmpty(incomingTarget) ? "none" : incomingTarget;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mode={matchMode}, tol={tolerance}, incomingSrc={isrc}, incomingDst={idst}");
        }
    }
}
