// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: blendManip
// Phase C implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("blendManip")]
    public sealed class MayaGenerated_BlendManipNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (blendManip)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float size;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            size = ReadFloat(0f, ".size", "size", ".s", "s");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, size={size}");
        }
    }
}
