// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: axisAngleToQuat
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("axisAngleToQuat")]
    public sealed class MayaGenerated_AxisAngleToQuatNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private Vector3 axis;
        [SerializeField] private float angleDeg;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            float ax = ReadFloat(0f, ".axisX", "axisX", ".ax", "ax");
            float ay = ReadFloat(0f, ".axisY", "axisY", ".ay", "ay");
            float az = ReadFloat(0f, ".axisZ", "axisZ", ".az", "az");
            axis = new Vector3(ax, ay, az);

            angleDeg = ReadFloat(0f, ".angle", "angle", ".a", "a");
            SetNotes($"{NodeType} '{NodeName}' decoded: axis={axis}, angle={angleDeg}");
        }
    }
}
