// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: containerBase
// Production implementation (non-empty decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("containerBase")]
    public sealed class MayaGenerated_ContainerBaseNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (containerBase)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string containerName;
        [SerializeField] private int memberCountHint;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            containerName = ReadString("", ".name", "name", ".containerName", "containerName");
            memberCountHint = ReadInt(0, ".memberCount", "memberCount", ".count", "count");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, name='{containerName}', memberCountHint={memberCountHint} (membership via connections preserved)");
        }
    }
}
