// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: bulletRigidBodyShape
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("bulletRigidBodyShape")]
    public sealed class MayaGenerated_BulletRigidBodyShapeNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (bulletRigidBodyShape)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float mass = 1f;
        [SerializeField] private float friction;
        [SerializeField] private float restitution;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            mass = ReadFloat(1f, ".mass", "mass", ".m", "m");
            friction = ReadFloat(0f, ".friction", "friction", ".mu", "mu");
            restitution = ReadFloat(0f, ".restitution", "restitution", ".bounce", "bounce", ".rest", "rest");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mass={mass}, friction={friction}, restitution={restitution} (no runtime bullet sim; attrs+connections preserved)");
        }
    }
}
