// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: componentTagBase
// Production implementation (non-empty decode; base-like node but still decoded)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("componentTagBase")]
    public sealed class MayaGenerated_ComponentTagBaseNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (componentTagBase)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string tagName;
        [SerializeField] private int tagCountHint;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            tagName = ReadString("", ".tagName", "tagName", ".name", "name");
            tagCountHint = ReadInt(0, ".tagCount", "tagCount", ".count", "count");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, tagName='{tagName}', tagCountHint={tagCountHint} (tags via attrs+connections preserved)");
        }
    }
}
