// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyAbsEnumOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyAbsEnumOverride")]
    public sealed class MayaGenerated_ApplyAbsEnumOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int enumValue;
        [SerializeField] private string sampleIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            enumValue = ReadInt(0, ".value", "value", ".enumValue", "enumValue", ".v", "v");
            sampleIncomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, enumValue={enumValue}, incoming={(string.IsNullOrEmpty(sampleIncomingPlug) ? "none" : sampleIncomingPlug)}");
        }
    }
}
