// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: assemblyDefinition
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("assemblyDefinition")]
    public sealed class MayaGenerated_AssemblyDefinitionNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private string definitionFile;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            definitionFile = ReadString("", ".fileName", "fileName", ".path", "path", ".definitionFile", "definitionFile");
            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, file='{definitionFile}'");
        }
    }
}
