// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyRel3FloatsOverride
// Phase C implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyRel3FloatsOverride")]
    public sealed class MayaGenerated_ApplyRel3FloatsOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private Vector3 value;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            float x = ReadFloat(0f, ".x", "x", ".valueX", "valueX", ".vx", "vx");
            float y = ReadFloat(0f, ".y", "y", ".valueY", "valueY", ".vy", "vy");
            float z = ReadFloat(0f, ".z", "z", ".valueZ", "valueZ", ".vz", "vz");
            value = new Vector3(x, y, z);

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, value={value}");
        }
    }
}
