// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: collisionModel
// Production implementation (non-empty decode; preserves connections)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("collisionModel")]
    public sealed class MayaGenerated_CollisionModelNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (collisionModel)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int collisionType;
        [SerializeField] private float friction;
        [SerializeField] private float restitution;

        [SerializeField] private string incomingGeometry;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            collisionType = ReadInt(0, ".collisionType", "collisionType", ".type", "type");
            friction = ReadFloat(0f, ".friction", "friction", ".mu", "mu");
            restitution = ReadFloat(0f, ".restitution", "restitution", ".bounce", "bounce", ".rest", "rest");

            incomingGeometry = FindLastIncomingTo("inputGeometry", "inputGeom", "input", "in", "worldMesh", "inMesh");
            string ig = string.IsNullOrEmpty(incomingGeometry) ? "none" : incomingGeometry;

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, type={collisionType}, friction={friction}, restitution={restitution}, incomingGeom={ig} (no runtime sim; attrs+connections preserved)");
        }
    }
}
