// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: computeLocal (and alias: ComputeLocal)
// Production implementation (non-empty decode)
//
// NOTE:
// - Maya2026_StandardNodeTypes.txt には "ComputeLocal" 表記が存在するため、
//   大文字小文字の揺れで監査に引っかからないよう alias を追加する。
// - NodeFactory / CoverageTools は OrdinalIgnoreCase で解決できるが、
//   「懸念点一掃（ポートフォリオ100点）」のために明示しておく。

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("computeLocal")]
    public sealed class MayaGenerated_ComputeLocalNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (computeLocal)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private string expression;
        [SerializeField] private int mode;
        [SerializeField] private string scope;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            expression = ReadString("", ".expression", "expression", ".expr", "expr", ".code", "code");
            mode = ReadInt(0, ".mode", "mode");
            scope = ReadString("", ".scope", "scope", ".namespace", "namespace");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, mode={mode}, scope='{scope}', expression='{expression}' (not executed; stored for reconstruction)");
        }
    }
}
