// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: basicSelector
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("basicSelector")]
    public sealed class MayaGenerated_BasicSelectorNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (basicSelector)")]
        [SerializeField] private int index;
        [SerializeField] private bool enabled = true;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            index = ReadInt(0, ".index", "index", ".i", "i", ".choice", "choice");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, index={index}");
        }
    }
}
