// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: boundary
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("boundary")]
    public sealed class MayaGenerated_BoundaryNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (boundary)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private float tolerance;
        [SerializeField] private string incomingCurveOrSurface;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            tolerance = ReadFloat(0f, ".tolerance", "tolerance", ".tol", "tol");
            incomingCurveOrSurface = FindLastIncomingTo("inputCurve", "ic", "inputSurface", "is", "input", "in");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, tolerance={tolerance}, incoming={(string.IsNullOrEmpty(incomingCurveOrSurface) ? "none" : incomingCurveOrSurface)}");
        }
    }
}
