// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: applyAbsIntOverride
// Production implementation (opaque decode; non-empty)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("applyAbsIntOverride")]
    public sealed class MayaGenerated_ApplyAbsIntOverrideNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (opaque)")]
        [SerializeField] private bool enabled = true;
        [SerializeField] private int value;
        [SerializeField] private string sampleIncomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            bool muted = ReadBool(false, ".mute", "mute", ".disabled", "disabled");
            bool explicitEnabled = ReadBool(true, ".enabled", "enabled", ".enable", "enable");
            enabled = !muted && explicitEnabled;

            value = ReadInt(0, ".value", "value", ".intValue", "intValue", ".v", "v");
            sampleIncomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: enabled={enabled}, value={value}, incoming={(string.IsNullOrEmpty(sampleIncomingPlug) ? "none" : sampleIncomingPlug)}");
        }
    }
}
