// PATCH: ProductionImpl v6 (Unity-only, retention-first)
// AUTO-GENERATED by MayaNodeCoverageTools
// NodeType: boolean
// Production implementation (non-empty, opaque decode)

using UnityEngine;
using MayaImporter;
using MayaImporter.Core;

namespace MayaImporter.Generated
{
    [DisallowMultipleComponent]
    [MayaNodeType("boolean")]
    public sealed class MayaGenerated_BooleanNode : MayaPhaseCNodeBase
    {
        [Header("Decoded (boolean)")]
        [SerializeField] private bool value;
        [SerializeField] private string incomingPlug;

        protected override void DecodePhaseC(MayaImportOptions options, MayaImportLog log)
        {
            value = ReadBool(false, ".output", "output", ".value", "value", ".v", "v");
            incomingPlug = FindLastIncomingTo("input", "in", "i", "value", "v");

            SetNotes($"{NodeType} '{NodeName}' decoded: value={value}, incoming={(string.IsNullOrEmpty(incomingPlug) ? "none" : incomingPlug)}");
        }
    }
}
